### ISSUE TITLE
Error during checkModel(HHmodelica.CompleteModels.HHelectric)

### ISSUE THREAD

**Issue by manuEbg** [CSchoel/hh-modelica#1]
I just checked the HHelectric model with our LspConsoleApplication and got the following result:
`[/home/swtp/modelica/hh-modelica/HHmodelica/CompleteModels/HHelectric.mo:15:50-15:57:writable] Error: Modified element g not found in class Conductor.`
The error occurs [here](https://github.com/CSchoel/hh-modelica/blob/422aa6050e8d306206eef2982b2b43476b6a7fde/HHmodelica/CompleteModels/HHelectric.mo#L15).

Is this a problem with our application, with me as a user:) or with the model itself?

**Comment by CSchoel** [comment]
Thanks for the Issue. There *was* an error in HH-modelica, which I just fixed, but this error pertained to `HHmono`, not `HHelectric`. Which version of the Modelica Standard Library (MSL/`Modelica`) are you using? The current default is version 4.0, but HH-modelica requires version 3.2.3.

**Comment by manuEbg** [comment]
Actually i have no Idea. The OMC-java-api just calls `loadModel(Modelica)` after it connects to omc. see [here](https://github.com/THM-MoTE/omc-java-api/blob/48c27b7d7c3eea3914be2a3c46f4c33112a8e5f6/src/main/java/omc/ZeroMQClient.java#L110)

**Comment by CSchoel** [comment]
Then I suggest you find a way to either a) parse the `uses` annotation in a package and load appropriate versions of required libraries and/or b) give the user the possibility to choose a desired model version in `loadModel()`. My comment was intended to nudge you to realize this yourself. :wink: 

For an example of how to load a specific version of a package, you can refer to the [script that I showed you in one of our first sessions](https://homepages.thm.de/~cslz90/kurse/swtp21/example_most.mos).
